feat(ssh-copy-id-sudo): refactor script to support multiple user@hostname arguments and check for existing SSH keys
The script is refactored to allow copying SSH keys to multiple hosts in a single execution. It also checks for existing SSH keys, prioritizing the use of an Ed25519 key if available, enhancing flexibility and usability for users.

diff --git a/files/.bin/ssh-copy-id-sudo b/files/.bin/ssh-copy-id-sudo
--- a/files/.bin/ssh-copy-id-sudo
+++ b/files/.bin/ssh-copy-id-sudo
@@ -2,39 +2,45 @@
 # ssh-copy-id-sudo: like ssh-copy-id but copy public key to root space
 # usage: ssh-copy-id-sudo user@host
 
-#!/bin/bash
+setup_root_ssh() {
+    # Extract the username and hostname
+    USER_HOST="$1"
+    HOSTNAME=$(echo "$USER_HOST" | cut -d'@' -f2)
 
-# Check if the user provided a hostname
-if [ "$#" -ne 1 ]; then
-    echo "Usage: $0 user@hostname"
+    # Copy the SSH public key using ssh and sudo to append it to the root's authorized_keys
+    # Only if it's not already present
+    ssh -t "$USER_HOST" "sudo sh -c '\
+        mkdir -p /root/.ssh && \
+        touch /root/.ssh/authorized_keys && \
+        chmod 600 /root/.ssh/authorized_keys && \
+        grep -q -F \"$PUB_KEY\" /root/.ssh/authorized_keys || echo \"$PUB_KEY\" >> /root/.ssh/authorized_keys \
+        '"
+
+    # Check if the SSH key was successfully processed
+    ssh -O exit root@"$HOSTNAME" &>/dev/null
+    if ssh -q root@"$HOSTNAME" exit; then
+        echo "SSH key successfully processed for $HOSTNAME root."
+    else
+        echo "Failed to process SSH key for $HOSTNAME root."
+    fi
+}
+
+if [[ "$#" -eq 0 ]]; then
+    echo "Usage: $0 user@hostname user@hostname2 ..."
     exit 1
 fi
 
-# Extract the username and hostname
-USER_HOST="$1"
-HOSTNAME=$(echo "$USER_HOST" | cut -d'@' -f2)
-
-# Check for an existing SSH key, generate one if not found
-if [ ! -f "$HOME/.ssh/id_rsa.pub" ]; then
-    echo "SSH key not found, generating one..."
-    ssh-keygen -t rsa -b 2048
-fi
-
-# Read the public SSH key
-PUB_KEY=$(cat "$HOME/.ssh/id_rsa.pub")
-
-# Copy the SSH public key using ssh and sudo to append it to the root's authorized_keys
-# Only if it's not already present
-ssh -t "$USER_HOST" "sudo sh -c '\
-    mkdir -p /root/.ssh && \
-    touch /root/.ssh/authorized_keys && \
-    chmod 600 /root/.ssh/authorized_keys && \
-    grep -q -F \"$PUB_KEY\" /root/.ssh/authorized_keys || echo \"$PUB_KEY\" >> /root/.ssh/authorized_keys \
-'"
-
-# shellcheck disable=SC2181
-if [ $? -eq 0 ]; then
-    echo "SSH key successfully processed for $HOSTNAME root."
+export PUB_KEY
+if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
+    PUB_KEY=$(cat "$HOME/.ssh/id_ed25519.pub")
+elif [[ -f "$HOME/.ssh/id_rsa.pub" ]]; then
+    PUB_KEY=$(cat "$HOME/.ssh/id_rsa.pub")
 else
-    echo "Failed to process SSH key for $HOSTNAME root."
+    echo "No public key found in ~/.ssh/ to copy to $USER_HOST."
+    exit 1
 fi
+
+while [[ $# -ge 1 ]]; do
+    setup_root_ssh "$1"
+    shift
+done
