featuring(bashrc): add functions for array manipulation and hook management
Enhance the bashrc functions by introducing array removal and hook management capabilities. This
improves the flexibility and usability of the script for users needing to manage hooks and arrays
efficiently.

diff --git a/files/.bashrc.d/02-functions b/files/.bashrc.d/02-functions
--- a/files/.bashrc.d/02-functions
+++ b/files/.bashrc.d/02-functions
@@ -20,10 +20,22 @@ ifs_restore() {
 }
 
 ifs_wrapper() {
+    # choose a special character that is not in the arguments to use as IFS
+    local i=1
+    # shellcheck disable=SC2059
+    choose_ifs=$(printf "\\$(printf %03o "$i")")
+    while [[ "$*" =~ $choose_ifs ]]; do
+        ((i++))
+        if ((i > 126)); then
+            echo "No more special characters available, ifs_wrapper failed" >&2
+            return 1
+        fi
+        # shellcheck disable=SC2059
+        choose_ifs=$(printf "\\$(printf %03o "$i")")
+    done
     [[ -n "${IFS+x}" ]] && local IFS_backup=$IFS
     trap 'ifs_restore; trap - RETURN' RETURN
-    IFS=$1
-    shift
+    IFS="$choose_ifs"
     "$@"
 }
 
@@ -38,7 +50,25 @@ array_contains() {
     local arr_name=$1
     local search_value=$2
 
-    ifs_wrapper $'\001' _array_contains "$arr_name" "$search_value"
+    ifs_wrapper _array_contains "$arr_name" "$search_value"
+}
+
+_array_remove() {
+    local -n _arr=$1
+    local search_value=$2
+    elm_string="$IFS${_arr[*]}$IFS"
+    elm_string="${elm_string//$IFS$search_value$IFS/$IFS}"
+    # string first and last $IFS
+    elm_string="${elm_string##"$IFS"}"
+    elm_string="${elm_string%%"$IFS"}"
+    # shellcheck disable=SC2206
+    _arr=($elm_string)
+}
+
+array_remove() {
+    local arr_name=$1
+    local search_value=$2
+    ifs_wrapper _array_remove "$arr_name" "$search_value"
 }
 
 patch_function() {
