修正(setup.d)：將common-lib的引用方式改為檢查檔案存在性
現在每個腳本都檢查common-lib檔案是否存在，若不存在則輸出錯誤訊息並退出。這樣的改動提高了腳本的穩定性，避免因為找不到common-lib而導致的錯誤。

diff --git a/setup.d/80-desktop-configs b/setup.d/80-desktop-configs
--- a/setup.d/80-desktop-configs
+++ b/setup.d/80-desktop-configs
@@ -1,6 +1,13 @@
 #!/bin/bash
 # vim: set et fenc=utf-8 ff=unix sts=4 sw=4 ts=8 :
-. common-lib
+common_lib="$(dirname "$(readlink -f "$0")")/common-lib"
+if [[ -f "$common_lib" ]]; then
+    # shellcheck source=common-lib
+    . "$common_lib"
+else
+    echo "Cannot find common-lib."
+    exit 1
+fi
 
 if [[ "$platform" == linux ]]; then
     # set moving window to Super+click
